{% set name = "loghub" %}
{% set version = "0.4.0" %}
{% set hash_type = "sha256" %}
{% set hash = "62e490be45b7d19d667de028c5858c6163ee715754a849092b5e17e878da5a0c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - loghub = loghub.cli.main:main
    - loghub-labels = loghub.cli.label_creator:main

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - jinja2
    - python

test:
  commands:
    - loghub --help
    - loghub-labels --help

about:
  home: https://github.com/spyder-ide/loghub
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Generate changelogs based on Github milestones or tags.
  description: |
    Generate changelogs based on Github milestones or tags.
  dev_url: https://github.com/spyder-ide/loghub

extra:
  recipe-maintainers:
    - ccordoba12
    - goanpeca
