travis:
  secure:
    BINSTAR_TOKEN: MBDiFjAEZ/oY7lfSGopVbxFOrgXgWMSvciVKvpJj+rwxNgr3309P02VESZXv/4vYnN3N5m4akBvD41xsYq6Ix+UPJcvciGGxZDTQPAFbHfU3zdfoF8xlaVF3lbTWP85xhcrFFW1XPD3Zfkjf6jwGheHS3yu0GQZZedKk7dVKsumWEk08N1FjegsfBBc/eYgCSDNBkISz+kURKG9N61L3OYChCf9hdEM06GF2zRuz1gDDnBoe4326+muBlGN6uGxkw7fxhwJ9aQaAdhLuMb9goB8A7OerEkvLl68k0DVZOjUp4aW41RsjGtkOzUcHojt//nlGm+r5Pa6a4h3fE3TBsqXOwoYvD8O1VV/HOz5kf8vp7iaOgMn4YmdkARRSZ3ogDnhTCYyfEWBiuJH1zQ56WMN/lzj39x8VC/zsTkD9DLGx63A8PKCbAqUrhjNFNjeVlJnvHXcRJtqRFvtQ+WV3CrzVvwJ+NwrV+e5/Gm6I526iy7AiflIdQiDmz9gZwZZWPJYaWtX7qv8L9J66cWBQ7VuBlEGK3Jw2V2IaiHuxkdl2KnxK4QaWl8Dam4BF31Mtq5DRZgrz9qejPue5A9ArBwFSkRu+PyIddBB4BQIWUZDps2Bei7IkRnOTWHk3znZWcJ3KKveayewUAVEbQzVAz6hzEIzYqtx6iRSSNump6A0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
